guide:
      - title: brand
        name: guide
        items:
              - title: color
                name: Color
              - title: font
                name: Typography
components:
      - title: summarize
        name: components
        items:
              - title: introduce
                name: introduction
      - title: component
        name: Components
        groups:
              - title: baseComponent
                items:
                      - title: button
                        name: Button
